name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Step to start JSON server
      - name: Start JSON server
        run: npm install -g json-server && json-server db.json --port=3000 --watch &

      # Step to start Angular app
      - name: Start Angular app
        run: npm install && npm start -- --port=4200 &

      # Wait for services to start
      - name: Wait for services
        run: sleep 10s # Adjust the time as needed to wait for the services to start

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: ''
          wait-on: 'http://localhost:4200' # Wait for Angular app to start
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
