name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2] # Adjust the number of parallel instances as needed
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start JSON Server
        run: npx json-server db.json --port=3000 & # Adjust the port as needed
      - name: Wait for JSON Server to start
        run: |
          while ! nc -z localhost 3000; do sleep 1; done
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:4200'
          record: true
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
